# docker build -t ss23485/fetcher .
FROM registry.cn-hangzhou.aliyuncs.com/ss-buaa/fetcher:v2.1

COPY target/content-server-0.0.1-SNAPSHOT.jar /app/content-server.jar

COPY start.sh /app/start.sh

ENTRYPOINT ["sh", "/app/start.sh"]