# docker build -t ss23485/fetcher .
FROM openjdk:8-jdk-alpine

COPY target/content-consumer-1.0-jar-with-dependencies.jar /app/content-consumer.jar

COPY start.sh /app/start.sh

ENTRYPOINT ["sh", "/app/start.sh"]
