# docker build -t ss23485/fetcher .
FROM registry.cn-hangzhou.aliyuncs.com/ss-buaa/fetcher

COPY target/content-consumer-1.0-jar-with-dependencies.jar /app/content-consumer.jar

COPY start.sh /app/start.sh

ENTRYPOINT ["sh", "/app/start.sh"]
